### ISSUE TITLE
Code of Conduct Proposal draft

### ISSUE THREAD

**Issue by orionblastar** [orionblastar/K666#10]
Under a creative commons license.

This could be a code of conduct for our projects that other people might want to use as well. Feel free to edit or change anything before we finish it and use it.

 #1 No drama or politics, issues should be about programming issues, feature requests, bug reports, and other stuff of a technical nature.
#2 If a contributor or admin or anyone else working on the project makes a social network or forum or other discussion on some other site, don't come here and request that person be removed from the project. People have different opinions on things and they have as much right to their opinion as you do. Having a different opinion does not mean you should censor them or throw them off a project. This repository is not about feelings, politics, drama, so we can focus on technical issues.
#3 If you want to join in just ask the contributors. If you can't program maybe you can find someone who does that can help? Besides programming you could contribute with the documentation and README.md files, even fixing spelling and grammar errors. If you speak a language other than English you could translate our documentation and README.md to another language.
#4 We value our time with our families and time off and etc. We can't be expected to code 24/7 so it will take some time to get through the issues. We do this work in our spare time to develop better free and open source software and this isn't the only repository we work on. So be patient with us getting to your issue. Usually we fix one issue at a time.
#5 If you are a feminist or social justice warrior joining Github looking for a fight. We believe in equal rights for everybody that includes freedom of speech for everybody. We don't care if your skin is green and your gender changes and you are from Mars or something, as long as you can write code and documentation and other stuff without getting into an debate with us. If you are a special little snowflake who gets triggered by GNU/Linux commands like 'kill' to stop a program, then don't join this repository and join some other one who can create a safe space. Be warned that we used to be trolls and have a thick skin to your insults and can trade you one for the other.
#6 Use a new branch when you are adding a feature or fixing an issue. Name the branch after what you are trying to do so it makes sense to us. Let us know what you are doing with it and test it out before you make a pull or push request.
#7 If you find copyrighted content tell the contributors about it so we can change it or delete it. Sometimes people put things in our repository or they end up there by mistake.
#8 Don't put passwords and API keys into this repository, hackers run robots looking for them and will steal your accounts and cost you money.
#9 If you submit bad code don't get upset by it, just learn from it. We all make mistakes and some people are still learning how to code. Ask for feedback on why the code was rejected, you might have forgotten to test it before putting it in the repository.
#10 Don't panic, anxiety and fear are the mind-killers. Take time off if you feel afraid, angry, have anxiety or some other thing. We want you at your best to write code for this repository. So take a break or something and find something to do that relieves stress.

**Comment by procrasti** [comment]
I think we can more or less agree to this... I'll be copying into procrasti/K666.

Gonna close this now.
