### ISSUE TITLE
Merge startup into master

### ISSUE THREAD

**Issue by procrasti** [orionblastar/K666#14]
## BUT DON'T DO IT DIRECTLY.

Priority: HIGHEST
Branch: mergetest

I want to see how your merge goes, and do the final merge myself, or at least check that a merge from it will create exactly what I want it to.

So:  **DON'T MERGE STARTUP INTO MASTER**

Instead, you want to branch master to a new branch (mergetest, from above), merge in the changes from startup into mergetest, fix anything and commit the changes (if something must be fixed), and then push the new branch to the github repository.

$ git clone https://github.com/orionblastar/K666 k6mergetest
$ cd k6mergetest
$ git checkout master       # Unless you've reset the default back to master, but doesn't hurt
$ git branch mergetest     # Create the mergetest branch
**$ git checkout startup**      # Get a local copy of startup
$ git checkout mergetest  # Switch to the mergetest branch, and work on it
$ git merge startup           # Bring in all the changes from startup, you might need to fix conflicts here

Make any other changes, but this is a mergetest branch, so rather, don't make any changes... more than likely.

**You will have to resolve the conflicts in REAMDE.md, and commit the changes.**

$ git push -u origin mergetest     # To push the new branch to the repository...

The mergetest branch should be trivial to merge into master and freek666, even with the github UI... You can feel free to merge into freek666 as you see fit... I'll merge mergetest into master for you, or at least check it.

**Comment by orionblastar** [comment]
Got an error:

 $ git merge startup
merge: startup - not something we can merge

Did you mean this?
    origin/startup
(env)norman@Lazarus0 ~/k6mergetest $ git merge origin/startup
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.
(env)norman@Lazarus0 ~/k6mergetest $

**Comment by procrasti** [comment]
Yes, that's exactly right...

> $ git merge startup
> merge: startup - not something we can merge
> 
> Did you mean this?
> origin/startup

Yep... doing merge from origin/startup takes the startup branch from the parent repository, the one you cloned from... in github... but you can do it locally too... but git doesn't know about startup yet (you haven't asked for it to be in your working directory), so you have to checkout startup, then checkout back to mergetest... there might be a shortcut for this, but:

<pre>$ git checkout startup
$ git checkout mergetest
$ git merge startup</pre>
But the result would be exactly the same... because there are changes in the same file in different branches that conflict, and cannot be automatically merged... You have to fix this by hand, add the changes for commit, then commit manually before you can push... This is the 'fix it if you have to' stage...
You'll probably find this branch merges easily with FreeK666, but not master... and I'm pretty happy to see that there is only one conflict (but we could have messed up in other ways... still, no worries).
So, fix this by hand... You should find the conflict pretty easily. It's in README.md, obviously... ummm, the lines start with <<<<<<<<<<<<<<<<<< ============= and >>>>>>>>>>>>>>>>... and you have to merge the two versions manually and remove all that noise... 
Then:
<pre>$ git add README.md
$ git commit       # whatever commit log entry you wish...
# YOU SHOULD REALLY TEST IT NOW, with k666-env and see it's all nice!!!
# Push this branch to the repository
$ git push -u origin mergetest
</pre>

**Comment by procrasti** [comment]
Alright... below is the README.md I get when I try this... 

You can see there are two conflicts in the file... The first one some difficulty in the 'title' (project name and tagline.), The second one in the project description.

You have to be intelligent to merge these things... clearly... the automated merger couldn't do it... it needs your help.

The first conflict has two changes... There's a full stop at the end of the first one... and the second one is all capitalised... Maybe you think the first is better than the second? Maybe you think they should be combined, capitalised and with a full stop at the end? You make the call.

The second conflict is between the description of K666 and of FreeK666... They are different things, we describe them differently... they should be different. Remember, we are merging into 'master', which should be the K666 project... So, I say take the HEAD version (the first one)...

```
<<<<<<< HEAD
# K666: Free Speech as in Open Source.
=======
# K666: Free Speech As In Open Source
>>>>>>> startup

procrasti@k5-stats.org

Forked by Orion Blastar for the FreeK666 project.
orionblastar@gmail.com

If you want to help or join contact Procrasti or Orion first.

# Instructions

## 1. Clone Source Repository
$ git clone https://github.org/orionblastar/K666
$ cd K666

## 2. Create the environment
$ . ./k666-env

This starts the server, it should start up ready.

## 3. Visit the site.
Go to http://localhost:8000/

## 4. Hooray!

We have begun.

# K666

<<<<<<< HEAD
K666 is a free and open source forum platform.
=======
FreeK666 is an attempt at making a free and open source version of Kr5ddit/K666

First stage we build a forum that anonymous users can use.

Then we add in the ability to register an account.

Future changes are adding credits which are earned by being voted up on comments and posts. Then adding subs like Reddit has by using tags.

The exchange will be trading credits for Bitcoin and vice versa. That way trolls are punished with negatvie credits and have to buy more to get back to normal user status.

Credit can be used to push your post to the top of the page. If you collect enough Credits you can sell them for Bitcoin.

Bitcoin and Credit market is based on the stock market.

The goal of this program is to create a forum that rewards users for good content and punishes trolls for bad content. There is an economic reward for posting good materials and some of the Bitcoins will go towards paying the hosting bill. This is a new startup business model that allows a forum to be free and the community moderates itself for reward of Credits.

The FreeK in FreeK666 sounds like Freak or could be short for Frequency or Frequency666 like a radio station or something.

FreeK666 also stands in free speech like in money, it allows people to exercise their free speech and up or down votes from the community determine what gets hidden and what gets shown and what makes it to the front page. So if the community is trolls, it will be troll conetent, if the community are more professional it will be a more professional site. Some of the current alpha testers are from Kuro5hin that had turned into a troll haven and eventually shut down, and from Reddit in which we write from scratch a discussion system which is where the name Kr5ddit comes from. Since SJWs took over Reddit and other sites, people want an alternative that they can run. But this forum is not based on Reddit but one of the goals is for it to replace Reddit and other discussion sites. Free Speech like in money that there are rewards of Kr5ddits to be sold for Bitcoins so the right kind of speech gets economically rewarded. There is also freedom and power given to the community to decide what is shown and what is hidden, instead of moderators and admins deciding what is shown and what is banned like in the Ellen Pao Reddit scandal.
>>>>>>> startup

If you want to contribute to this project contact the contributors.
```

**Comment by procrasti** [comment]
Removed you from every other issue, so you know this is the one I need you to finish asap.

**Comment by orionblastar** [comment]
I think I resolved it, but I am not 100% sure. 

https://github.com/orionblastar/K666/tree/mergetest

**Comment by procrasti** [comment]
Yep... I think this is done!

Good work.

Now you know how to resolve conflicts if there are any in the future.

This branch should merge cleanly with master, and then master should merge with FreeK666 and vice versa too, without issue.

Good stuff!

I'll let you close this one.

**Comment by procrasti** [comment]
This is done... now merged into master... will remove the branches too from github.
