### ISSUE TITLE
Create a Dynamic Template

### ISSUE THREAD

**Issue by procrasti** [orionblastar/K666#3]
NewBranch: DynamicIndex

echo "HELLO TEMPLATES" > freek666/templates/index.html

Add the following line to freek666/urls.py:
url(r'^index.html$', TemplateView.as_view(template_name="index.html")),

Now go to /index.html and it you should see HELLO TEMPLATES.

Additional Credit: Redirect root (/) to index.html.

**Comment by orionblastar** [comment]
I tried that but the index.html with the golden apple shows up instead of the template. Should the template directory be in freek666 or static?

**Comment by procrasti** [comment]
> Should the template directory be in freek666 or static?

echo "HELLO TEMPLATES" > freek666/templates/index.html

It's not static, so no.

The link to it is /index.html... you shouldn't see an apple.

**Comment by orionblastar** [comment]
I made the template directory in freek666 made the templates directory in freek666 echoed the index.html file there in templates. Started the K666-env and I still see the golden apple.

I got root redirected to static/index.html that has the Apple but I can't see the Hello.

**Comment by procrasti** [comment]
Don't go to static/index.html, just index.html.

**Comment by procrasti** [comment]
Actually, add a link from the static page to the dynamic page!

**Comment by procrasti** [comment]
This is fixed in startup branch.

Once you have merged it... feel free to close this issue.

**Comment by procrasti** [comment]
> Additional Credit: Redirect root (/) to index.html.

I think you can merge startup into master if everything looks good to you?

**Comment by procrasti** [comment]
Do this first: https://github.com/orionblastar/K666/issues/14

**Comment by procrasti** [comment]
We'll, we have this in mergetest now... will close.
