### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by procrasti** [orionblastar/K666#32]
You need to create an account on travis-ci.org, and enable building of the orionblastar/K666 repository.

Build success or failure doesn't matter, we'll be able to update the .travis.yml file afterwards to get it working, but I cannot enable your repository for you.

**Comment by orionblastar** [comment]
I went to Travis CI and enabled this repo. I'm not sure what settings it needs, but it should be in synch with this repo here on Github.

**Comment by procrasti** [comment]
You have to go to your profile page and select the repositories you want to build:

https://travis-ci.org/profile/orionblastar

It doesn't look like you've activated K666 yet.

**Comment by orionblastar** [comment]
I thought I did activate it, I went there and it wasn't activated, so I flipped the switch again to make sure it is activated now. This is confusing because I followed all of their steps, and the switch was flipped off when I just visited it a few minutes ago.

Is it on now?

**Comment by procrasti** [comment]
Yep, it seems to be working!!!

Just the build and testing intructions are wrong in the .travis.yml file, but we'll (or I'll) fix that later.

I'll close this one out.

Hows the tutorial going?

**Comment by orionblastar** [comment]
I'm still stumbling through it on part 1. Source is not found on my Linux, and apt-get install source is not found in Linux Mint apt. Is the apt package named something else?
