### ISSUE TITLE
Possible Trademark dispute

### ISSUE THREAD

**Issue by orionblastar** [orionblastar/K666#39]
[http://www.trademarkia.com/kuro5hin-technology-and-culture-from-the-trenches-86288781.html](http://www.trademarkia.com/kuro5hin-technology-and-culture-from-the-trenches-86288781.html)

Sye had filed a trademark as Kuro5hin was failing. 

We use CSS from Kuro5hin, possibly to develop a different CSS to avoid any trademark issues.

**Comment by allthingsgo** [comment]
I'd call that precaution anally attentative... CSS theme is considered to be enveloped under intellectual property now? that is news to me...

**Comment by orionblastar** [comment]
OK Sye, then we are alright using the CSS sheet and does not infringe on your Kuro5hin trademark?

**Comment by allthingsgo** [comment]
I'm closing this. No more intercourse.

**Comment by procrasti** [comment]
Yep... it's not the same CSS anyway... it just looks the same... I built it from scratch.
