### ISSUE TITLE
Create a FreeK666 Repository

### ISSUE THREAD

**Issue by procrasti** [orionblastar/K666#4]
Okay, Git only allows you to fork someone else's respository, and only for the same name, so this is how we're going to create a FreeK666 repository.
1. Move the K666 repository out of the way, say, K666-OB
2. Fork procrasti/K666 to OB/K666
3. Rename OB/K666 to OB/FreeK666
4. Move K666 back, Rename K666-OB to K666
5. Merge in everything from the FreeK666 branch into the FreeK666 repository.

Done!

**Comment by orionblastar** [comment]
No good I moved OB/K666 to OB/K666-OB but when I went to fork your K666 it was grayed out for forking it in my profile because it is already forked. It didn't work because Github limits what you can fork. The SJWs got control here I think we might have to host it on Bitbucket under a different name?

**Comment by procrasti** [comment]
LOL... that's crazy huh...

Let's keep going, just for lols...

Alright, so abort that plan, and rename it back to what it was...

We will create a good FreeK666 repository by the end of this.

Although I'm sure we'd have it done by now on bitbucket...

BTW: You CAN actually fork procrasti here from bitbucket.

**Comment by procrasti** [comment]
Huh!!!

The answer lies in NOT initialising the repository.

There are instructions what to do next there...

So: 
1. Clone a copy of your K666 to your local machine.
2. Create a new repository for your FreeK666, You may find the FreeK666backup project is messing you up, lets call it FreeK6661 if or something... we can delete whatever we like later on... if this works.
3. "push an existing repository from the command line", the third one down when you created
   the FreeK6661 repository. This will make FreeK6661 a fork of your K666 repository.
4. Let me know it worked.

**Comment by procrasti** [comment]
Not initialising a repository looks something like this: https://github.com/procrasti/Freek666

We can fork it from anything!

**Comment by procrasti** [comment]
Yeah, I don't think you should have deleted the FreeK666backup project... at the very least it contained a few issues that we fixed (?)... but it should have freed up the FreeK666 project name in github for a do over... I just think we should have done that later.

Which is why I suggested you create a new repository called FreeK6661 (Note the 1!!) in your account, do the command line stuff from git to make it a fork of procrasti/K666 or of orionblaster/K666(FreeK666) or is it better to track orionblaster/K666(master)?... and bought in any remaining changes.

Ce La Vie... We're learning... and while the initial curve is steep, we're making good progress... You're already getting the hang of git quite quickly... but there'll always be some edge case we will learn from.

**Comment by procrasti** [comment]
I'm watching you do this... and seeing how it goes... Might be out of date by the time you read this...  I think it's pretty clear (to me) that this should be a fork of procrasti/K666, not orionblaster/K666... try that?

But I'm getting less confident that github will correctly keep track of the project (ie, saying that it is a fork or procrasti/K666)... Maybe the fact is that you can't keep tracked forks of the same project in different repositories in a single account?

Well, let's see... Try out every avenue.

**Comment by procrasti** [comment]
(From the issue I created in FreeK6661):

I really don't mind now, what you do with this... as long as you can merge... it should all be good.

So, back to orionblastar/K666... That should be the main repository you work on, because almost everything at this stage should be common to both.

We really should be doing most of our work from orionblaster/K666(master) from which I will merge all changes back to procrasti/K666 and from there into kr5ddit.

Keep FreeK666 up to date with K666... but generally you won't be working on FreeK666... Only things that are completely specific to it should go in that repository.

We should keep the FreeK666 Branch in K666, but you might want to branch 'freek666' from that, and remove the old branch once that's in... The freek666 branch should match the FreeK666 repository identically, after merging. Again, the only difference between freek666 and master are for FreeK666 ONLY (or specifically)... that don't apply to K666.

So, we should change the default branch back to master... and we should branch from master for 99% of the work... If in doubt, still branch from master, because it will be trivial to merge into freek666 and FreeK666 instead... but most branches will be merged into master and destroyed after we know they are 'good'. (I'll copy this into the K666 issue, incase you decide to restart this repo!).

**Comment by procrasti** [comment]
So... To sum up, what I think needs to be done:

Branch orionblastar/K666(FreeK666) to orionblaster/K666(freek666)... and delete orionblastar/K666(FreeK666)... Just because lowercase is easier, and differentiates the branch from the repository...

Make orionblaster/K666(master) the default branch.

Sync freek666 with FreeK666... however you do it... but don't be copying files about... use pull or merge or whatever git commands to do it. At the end of this, they should be identical.

You might want to merge startup into freek666, make sure that it is what you want for freek666 (doesn't remove anything freek666 specific)... and check that everything is working... and what is new/shinier...

Then sync FreeK666 with freek666 again... Ensure they are IDENTICAL (again, try not to do filesystem based copies and commits... you should almost always be merging and pulling, and fixing up conflicts or whatever.

Ummm... yeah... that's mostly it... also sync freek666 with FreeK666.

I'm happy to close this issue when you're confident you all that.

**Comment by procrasti** [comment]
Please don't merge startup into main just yet... I'll do that...

You can merge it into freek666, and check that all works how YOU want it to... and I'll merge into master and check that all looks like I want it to...

While you can, for sure, merge as you please into master, please remember that it is NOT FreeK666... it is K666...

**Comment by procrasti** [comment]
Do this first: https://github.com/orionblastar/K666/issues/14

**Comment by procrasti** [comment]
I think this is done... and you can close it, right?

**Comment by procrasti** [comment]
I'm still having trouble merging master into FreeK666 WITHOUT leaving the FreeK666 README.md in place... strange?

**Comment by procrasti** [comment]
I'm not going to worry about this... let's close this and continue as we're making progress however we get there.
