### ISSUE TITLE
Customise Template

### ISSUE THREAD

**Issue by procrasti** [orionblastar/K666#5]
Depends: https://github.com/orionblastar/K666/issues/3
BranchName: showusername

Show the logged in users username:

Add this to templates/index.html

----- BEGIN CHANGES TO templates/index.html ----
Hello
{% with request.user as user %}
    {% if user.is_authenticated %}
        {{ user.username }}
    {% else %}
        Anonymous
    {% endif %}
{% endwith %}
----- END CHANGES TO templates/index.html ----

**Comment by orionblastar** [comment]
There is no templates directory, should I create it in freek666/static/templates/ ?

**Comment by procrasti** [comment]
No, it's not static...

~/src/k666/freek666/templates/index.html

But you got solve #3 first.

**Comment by procrasti** [comment]
This is working in branch startup...

Please close this issue when you have it working.

**Comment by procrasti** [comment]
Do this first: https://github.com/orionblastar/K666/issues/14

**Comment by procrasti** [comment]
Once you test that this is in mergetest, you can close this case.

Also, you might want to merge mergetest into your FreeK666 branch... then test that you have a dynamic page there... then close this one.

Basically, assigning to you to close.

**Comment by procrasti** [comment]
This is now in master... will close.
